# Generated by Django 5.0.2 on 2024-04-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Majdoor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_db',
            old_name='username',
            new_name='c_id',
        ),
    ]
