# Generated by Django 5.0.2 on 2024-04-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Majdoor', '0002_rename_username_users_db_c_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_db',
            name='id',
        ),
        migrations.AlterField(
            model_name='users_db',
            name='c_id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='users_db',
            name='password',
            field=models.CharField(max_length=50, null=True, verbose_name='Password'),
        ),
    ]
