# Generated by Django 5.0.2 on 2024-04-05 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Majdoor', '0003_remove_users_db_id_alter_users_db_c_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_db',
            old_name='c_id',
            new_name='cu_id',
        ),
    ]
