# Generated by Django 5.0.2 on 2024-04-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Majdoor', '0004_rename_c_id_users_db_cu_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_db',
            old_name='cu_id',
            new_name='c_id',
        ),
    ]
